#!/command/with-contenv bash
# SPDX-FileCopyrightText: © 2026 Nfrastack <code@nfrastack.com>
#
# SPDX-License-Identifier: MIT

source /container/base/functions/container/init
prepare_service
SERVICE_NAME="docker-socket-proxy"

if [ ! -f "/container/state/restart" ] ; then
    #socketproxy_sanity_test
    socketproxy_setup_container_mode
    socketproxy_configure_nginx
fi

liftoff
